meethodu/config/routes.rb
Meethodu::Application.routes.draw do

  root :to => "sessions#new"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'about' => :about
    get 'howit' => :howit
    get 'whyit' => :whyit
    get 'doesit' => :doesit
    get 'faq' => :faq
    get 'contact' => :contact

  end

  controller :profile do
    get 'profile' => :show
  end

  controller :friendship_sent_requests do
    post 'add_friend' => :create
    post 'friendship_sent_requests' => :create
    delete 'reject_friend' => :destroy
  end

  controller :logout do
    get 'logout' => :new
  end

  controller :projects do
    get 'my_projects' => :my_projects
  end

  controller :my_contributions do
    get 'my_contributions' => :get_my_contributions
  end
  resources :friendship_sent_requests

  controller :donor_requests do
    post '/donor_requests/accept' => :accept
    post '/donor_requests/reject' => :reject
    post '/donor_requests/yes_got_money' => :yes_got_money
    post '/donor_requests/no_money' => :no_money
  end
  resources :donor_requests

  resources :receiver_requests

  resources :project_fundings

  resources :projects

  resources :friendships

  resources :users

  resources :test_products

end

meethodu/app/models/receiver_request.rb
class ReceiverRequest < ActiveRecord::Base
end

meethodu/app/controllers/receiver_requests_controller.rb
class ReceiverRequestsController < ApplicationController
  # GET /receiver_requests
  # GET /receiver_requests.xml
  def index
    @receiver_requests = ReceiverRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @receiver_requests }
    end
  end

  # GET /receiver_requests/1
  # GET /receiver_requests/1.xml
  def show
    @receiver_request = ReceiverRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @receiver_request }
    end
  end

  # GET /receiver_requests/new
  # GET /receiver_requests/new.xml
  def new
    @receiver_request = ReceiverRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @receiver_request }
    end
  end

  # GET /receiver_requests/1/edit
  def edit
    @receiver_request = ReceiverRequest.find(params[:id])
  end

  # POST /receiver_requests
  # POST /receiver_requests.xml
  def create
    @receiver_request = ReceiverRequest.new(params[:receiver_request])

    respond_to do |format|
      if @receiver_request.save
        format.html { redirect_to(@receiver_request, :notice => 'Receiver request was successfully created.') }
        format.xml  { render :xml => @receiver_request, :status => :created, :location => @receiver_request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @receiver_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /receiver_requests/1
  # PUT /receiver_requests/1.xml
  def update
    @receiver_request = ReceiverRequest.find(params[:id])

    respond_to do |format|
      if @receiver_request.update_attributes(params[:receiver_request])
        format.html { redirect_to(@receiver_request, :notice => 'Receiver request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @receiver_request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /receiver_requests/1
  # DELETE /receiver_requests/1.xml
  def destroy
    @receiver_request = ReceiverRequest.find(params[:id])
    @receiver_request.destroy

    respond_to do |format|
      format.html { redirect_to(receiver_requests_url) }
      format.xml  { head :ok }
    end
  end
end

meethodu/app/helpers/receiver_requests_helper.rb
module ReceiverRequestsHelper
end

meethodu/app/views/receiver_requests/_form.html.erb
<%= form_for(@receiver_request) do |f| %>
  <% if @receiver_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver_request.errors.count, "error") %> prohibited this receiver_request from being saved:</h2>

      <ul>
      <% @receiver_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :received %><br />
    <%= f.check_box :received %>
  </div>
  <div class="field">
    <%= f.label :received_date %><br />
    <%= f.date_select :received_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

meethodu/app/views/receiver_requests/edit.html.erb
<h1>Editing receiver_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @receiver_request %> |
<%= link_to 'Back', receiver_requests_path %>

meethodu/app/views/receiver_requests/index.html.erb
<h1>Listing receiver_requests</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Received</th>
    <th>Received date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receiver_requests.each do |receiver_request| %>
  <tr>
    <td><%= receiver_request.project_id %></td>
    <td><%= receiver_request.received %></td>
    <td><%= receiver_request.received_date %></td>
    <td><%= link_to 'Show', receiver_request %></td>
    <td><%= link_to 'Edit', edit_receiver_request_path(receiver_request) %></td>
    <td><%= link_to 'Destroy', receiver_request, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receiver request', new_receiver_request_path %>

meethodu/app/views/receiver_requests/new.html.erb
<h1>New receiver_request</h1>

<%= render 'form' %>

<%= link_to 'Back', receiver_requests_path %>

meethodu/app/views/receiver_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @receiver_request.project_id %>
</p>

<p>
  <b>Received:</b>
  <%= @receiver_request.received %>
</p>

<p>
  <b>Received date:</b>
  <%= @receiver_request.received_date %>
</p>


<%= link_to 'Edit', edit_receiver_request_path(@receiver_request) %> |
<%= link_to 'Back', receiver_requests_path %>