meethodu/config/routes.rb
Meethodu::Application.routes.draw do

  root :to => "sessions#new"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'about' => :about
    get 'howit' => :howit
    get 'whyit' => :whyit
    get 'doesit' => :doesit
    get 'faq' => :faq
    get 'contact' => :contact

  end

  controller :profile do
    get 'profile' => :show
  end

  controller :friendship_sent_requests do
    post 'add_friend' => :create
    post 'friendship_sent_requests' => :create
    delete 'reject_friend' => :destroy
  end

  controller :logout do
    get 'logout' => :new
  end

  controller :projects do
    get 'my_projects' => :my_projects
  end

  controller :my_contributions do
    get 'my_contributions' => :get_my_contributions
  end
  resources :friendship_sent_requests

  controller :donor_requests do
    post '/donor_requests/accept' => :accept
    post '/donor_requests/reject' => :reject
    post '/donor_requests/yes_got_money' => :yes_got_money
    post '/donor_requests/no_money' => :no_money
  end
  resources :donor_requests

  resources :receiver_requests

  resources :project_fundings

  resources :projects

  resources :friendships

  resources :users

  resources :test_products

end

meethodu/app/models/donor_request.rb
class DonorRequest < ActiveRecord::Base
  validates :project_id, :sent_money, :sent_date, :sent_user_id, :presence => true
end

meethodu/app/models/friendship.rb
class Friendship < ActiveRecord::Base
    validates :friend1_id, :friend2_id, :begin_date, :presence => true
    belongs_to :user
end

meethodu/app/models/friendship_sent_request.rb
class FriendshipSentRequest < ActiveRecord::Base
    validates :from_user, :to_user, :message, :presence => true
    belongs_to :users
end

meethodu/app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :summary, :description,  :maximum_budget, :days_to_return_money, :user_id, :presence => true
  
end

meethodu/app/models/project_funding.rb
class ProjectFunding < ActiveRecord::Base
end

meethodu/app/models/receiver_request.rb
class ReceiverRequest < ActiveRecord::Base
end

meethodu/app/models/test_product.rb
class TestProduct < ActiveRecord::Base
end

meethodu/app/models/user.rb
class User < ActiveRecord::Base
    
    validates :first_name, :last_name, :user_id, :presence => true
    validates :user_id, :uniqueness => true
    validates :password, :confirmation => true

    validates :password_confirmation, :presence => true
    has_many :friendship

    def User.authenticate(userid,password)
      if user = find_by_user_id(userid)
        if user.password == password
          user
        end
      end
    end

end

meethodu/app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  def new
    session[:user_id] = 0
    session[:login_status] = 0
    session[:user_text_id] = 0
    session[:first_name] = ''
    session[:last_name] = ''
    respond_to do |format|
        format.html { redirect_to(login_path, :notice => 'You are successfully logged out') }
        format.xml  { render :xml => @friendship, :status => :created, :location => @friendship }
    end
  end

end

meethodu/app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index

   
  end

  def show
    if(session[:user_id] == 0)
      redirect_to(login_url)
      return
    end
    @user = User.find_by_user_id(session[:user_text_id])
    @friends = User.joins("INNER JOIN friendships on friendships.friend1_id = users.user_id").where("friendships.friend2_id = ?", session[:user_text_id])
    @incoming_friend_users = User.joins("INNER JOIN friendship_sent_requests on friendship_sent_requests.from_user = users.user_id").where("friendship_sent_requests.to_user = ?", session[:user_text_id])
    @incoming_donation_requests = DonorRequest.joins("INNER JOIN projects on donor_requests.project_id = projects.id ").where("projects.user_id = ?", session[:user_text_id]).find_all_by_seen_by_receiver(false)
    @incoming_sent_money_updates = DonorRequest.joins("INNER JOIN projects on donor_requests.project_id = projects.id ").where(" projects.user_id = ?", session[:user_text_id]).find_all_by_sent_and_sponsor_received_money(true,false)
  end

  def create
  end

  def edit
  end

end

meethodu/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @user = User.find(session[:user_id])
    if @user
      redirect_to(:action => show)
    else
      @users = User.all

      respond_to do |format|
       format.html # index.html.erb
       format.xml  { render :xml => @users }
      end
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @friend_projects = Project.where("user_id = ?",@user.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    if(session[:user_id] == 0)
      @user = User.new
    else
      @user = User.find(session[:user_id])
    end


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(session[:user_id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    if(params[:captcha] != 'upeckshin')
      redirect_to("/users/new/", :notice => 'Image text you entered is wrong.')
      # render :action => "new", :alert => 'Image text you entered is wrong.'
      return
    end
    respond_to do |format|
      if @user.save
        session[:login_status] = 1
        session[:user_id] = @user.id
        session[:user_text_id] = @user.user_id
        session[:first_name] = @user.first_name
        session[:last_name] = @user.last_name

        format.html { redirect_to(profile_url, :alert => 'User was successfully created.') }

      else
        format.html { render :action => "new" }

      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(session[:user_id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(profile_url, :alert => 'User was successfully updated.') }

      else
        format.html { render :action => "edit" }

      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:user_id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

meethodu/app/helpers/application_helper.rb
module ApplicationHelper
end

meethodu/app/helpers/donor_requests_helper.rb
module DonorRequestsHelper
end

meethodu/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

meethodu/app/helpers/logout_helper.rb
module LogoutHelper
end

meethodu/app/helpers/profile_helper.rb
module ProfileHelper
end

meethodu/app/helpers/projects_helper.rb
module ProjectsHelper
end

meethodu/app/helpers/sessions_helper.rb
module SessionsHelper
end

meethodu/app/helpers/test_products_helper.rb
module TestProductsHelper
end

meethodu/app/helpers/users_helper.rb
module UsersHelper
end

meethodu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="shortcut icon" href="favicon.ico" />
  <meta name="msvalidate.01" content="54C8F5898C73376F744631066D83A760" />
  <title>Meethodu - Help and Receive help from your friends</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "meethodu", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id="mee_body">
	<div id="mee_banner">
          <a href="<%= profile_path %> ">
		<%= image_tag("meethodu_tree_logo_small.png") %>

          </a>


	</div>
        <div id="nav_banner">

                <%if (session[:login_status] == 0) %>
                    <%= link_to 'All Projects', projects_path %>
                    <%= link_to 'Login', login_path %>

                <%elsif (session[:login_status] == 1)%>
                              <%= link_to 'Logout', logout_path %>
                              <% @login_user=User.find(session[:user_id]) %>
                              <%= link_to 'Edit Profile', edit_user_path(@login_user) %>
                              <%= link_to 'My Contributions', my_contributions_path%>
                              <%= link_to 'All Projects', projects_path %>
                              <%= link_to 'My Projects', my_projects_path%>
                              <%= link_to 'Create Project', new_project_path %>                             
                              <%= link_to 'Friends', profile_path %>
                              <%= link_to 'Home', profile_path %>
                              <a>Welcome <%= session[:first_name] %>, <%=  session[:last_name] %> ! </a>
                <%end %>

        </div>

	<div id="mee_main">
		<%= yield %>
	</div>
        <div id="mee_footer">
		<ul id="mee_footer_list_faq">
                        <li>
				<a href="doesit">Does it really work? </a>
			</li>

			<li>
				<a href="whyit">Why are you doing this? </a>
			</li>
                        <li>
				<a href="howit">How Does it work? </a>
			</li>

                </ul>
                <ul id="mee_footer_list_contacts">
			<li>
				<a href="faq">FAQ</a>
			</li>
			<li>
				<a href="/about">About Us</a>
			</li>
			<li>
				<a href="contact">Contact Us</a>
			</li>
		</ul>
        </div>
</body>
</html>