meethodu/config/routes.rb
Meethodu::Application.routes.draw do

  root :to => "sessions#new"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'about' => :about
    get 'howit' => :howit
    get 'whyit' => :whyit
    get 'doesit' => :doesit
    get 'faq' => :faq
    get 'contact' => :contact

  end

  controller :profile do
    get 'profile' => :show
  end

  controller :friendship_sent_requests do
    post 'add_friend' => :create
    post 'friendship_sent_requests' => :create
    delete 'reject_friend' => :destroy
  end

  controller :logout do
    get 'logout' => :new
  end

  controller :projects do
    get 'my_projects' => :my_projects
  end

  controller :my_contributions do
    get 'my_contributions' => :get_my_contributions
  end
  resources :friendship_sent_requests

  controller :donor_requests do
    post '/donor_requests/accept' => :accept
    post '/donor_requests/reject' => :reject
    post '/donor_requests/yes_got_money' => :yes_got_money
    post '/donor_requests/no_money' => :no_money
  end
  resources :donor_requests

  resources :receiver_requests

  resources :project_fundings

  resources :projects

  resources :friendships

  resources :users

  resources :test_products

end

meethodu/app/models/friendship_sent_request.rb
class FriendshipSentRequest < ActiveRecord::Base
    validates :from_user, :to_user, :message, :presence => true
    belongs_to :users
end

meethodu/app/controllers/friendship_sent_requests_controller.rb
class FriendshipSentRequestsController < ApplicationController
  # GET /friendship_sent_requests
  # GET /friendship_sent_requests.xml
  def index
    @friendship_sent_requests = FriendshipSentRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friendship_sent_requests }
    end
  end

  # GET /friendship_sent_requests/1
  # GET /friendship_sent_requests/1.xml
  def show
    @friendship_sent_request = FriendshipSentRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @friendship_sent_request }
    end
  end

  # GET /friendship_sent_requests/new
  # GET /friendship_sent_requests/new.xml
  def new
    @friendship_sent_request = FriendshipSentRequest.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /friendship_sent_requests/1/edit
  def edit
    @friendship_sent_request = FriendshipSentRequest.find(params[:id])
  end

  # POST /friendship_sent_requests
  # POST /friendship_sent_requests.xml
  def create
    @friendship_sent_request = FriendshipSentRequest.new
    @to_user= User.find_by_user_id(params[:friend_request_user_field_id])
    if(!@to_user )
         redirect_to(profile_path, :alert => "Userid you entered is wrong. You entered: #{params[:friend_request_user_field_id]}")
         return
    end
    if((session[:user_text_id] == params[:friend_request_user_field_id]) )
          redirect_to(profile_path, :alert => "Sorry! But You entered your own userid :)")
          return
    end

    @existing_request = FriendshipSentRequest.find_by_from_user_and_to_user(session[:user_text_id],params[:friend_request_user_field_id])
    if(@existing_request)
         redirect_to(profile_path, :alert => "Please be patient. You already sent a friend request to: #{params[:friend_request_user_field_id]}")
         return
    end

    @already_friends = Friendship.find_by_friend1_id_and_friend2_id(session[:user_text_id],params[:friend_request_user_field_id])
    if(@already_friends)
         redirect_to(profile_path, :alert => "Funny! No friendship request sent. You are already friends with: #{params[:friend_request_user_field_id]}")
         return
    end

    @friendship_sent_request.from_user = session[:user_text_id]
    @friendship_sent_request.to_user = params[:friend_request_user_field_id]
    @friendship_sent_request.message = params[:friend_request_message_field_id]
    @friendship_sent_request.sent_date = Time.now

    respond_to do |format|
      if @friendship_sent_request.save
        format.html { redirect_to(profile_path, :alert => "Your friendship request was successfully sent to #{params[:friend_request_user_field_id]}") }

      else
        format.html { redirect_to(profile_path, :alert => "Errors occured in sending friendhsip request. Did you enter introduction message?") }

      end
    end
  end

  # PUT /friendship_sent_requests/1
  # PUT /friendship_sent_requests/1.xml
  def update
    @friendship_sent_request = FriendshipSentRequest.find(params[:id])

    respond_to do |format|
      if @friendship_sent_request.update_attributes(params[:friendship_sent_request])
        format.html { redirect_to(profile_url, :notice => 'Friendship sent request was successfully updated.') }

      else
        format.html { render :action => "edit" }

      end
    end
  end

  # DELETE /friendship_sent_requests/1
  # DELETE /friendship_sent_requests/1.xml
  def destroy
    destroy_friendship_sent_request()
    respond_to do |format|
      format.html { redirect_to(:back, :notice => "Friendship request from #{params[:id]} was rejected") }
      format.xml  { head :ok }
    end
  end
end

meethodu/app/helpers/friendship_sent_requests_helper.rb
module FriendshipSentRequestsHelper
end

meethodu/app/views/friendship_sent_requests/_form.html.erb
<%= form_for(@friendship_sent_request) do |f| %>
  <% if @friendship_sent_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship_sent_request.errors.count, "error") %> prohibited this friendship_sent_request from being saved:</h2>

      <ul>
      <% @friendship_sent_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
        <%= label_tag(:enter_your_friend_UserID) %>
        <%= text_field_tag(:friend_request_user_field_id) %>
  </div>
  <div class="field">
        <%= label_tag(:enter_introduction_message) %>
        <%= text_field_tag(:friend_request_message_field_id) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

meethodu/app/views/friendship_sent_requests/edit.html.erb
<h1>Editing friendship_sent_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship_sent_request %> |
<%= link_to 'Back', friendship_sent_requests_path %>

meethodu/app/views/friendship_sent_requests/index.html.erb
<h1>Listing friendship_sent_requests</h1>

<table>
  <tr>
    <th>From user</th>
    <th>To user</th>
    <th>Message</th>
    <th>Sent date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendship_sent_requests.each do |friendship_sent_request| %>
  <tr>
    <td><%= friendship_sent_request.from_user %></td>
    <td><%= friendship_sent_request.to_user %></td>
    <td><%= friendship_sent_request.message %></td>
    <td><%= friendship_sent_request.sent_date %></td>
    <td><%= link_to 'Show', friendship_sent_request %></td>
    <td><%= link_to 'Edit', edit_friendship_sent_request_path(friendship_sent_request) %></td>
    <td><%= link_to 'Destroy', friendship_sent_request, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship sent request', new_friendship_sent_request_path %>

meethodu/app/views/friendship_sent_requests/new.html.erb
<h1>Send new friendship Request</h1>

<%= render 'form' %>

meethodu/app/views/friendship_sent_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From user:</b>
  <%= @friendship_sent_request.from_user %>
</p>

<p>
  <b>To user:</b>
  <%= @friendship_sent_request.to_user %>
</p>

<p>
  <b>Message:</b>
  <%= @friendship_sent_request.message %>
</p>

<p>
  <b>Sent date:</b>
  <%= @friendship_sent_request.sent_date %>
</p>


<%= link_to 'Edit', edit_friendship_sent_request_path(@friendship_sent_request) %> |
<%= link_to 'Back', friendship_sent_requests_path %>