meethodu/config/routes.rb
Meethodu::Application.routes.draw do

  root :to => "sessions#new"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'about' => :about
    get 'howit' => :howit
    get 'whyit' => :whyit
    get 'doesit' => :doesit
    get 'faq' => :faq
    get 'contact' => :contact

  end

  controller :profile do
    get 'profile' => :show
  end

  controller :friendship_sent_requests do
    post 'add_friend' => :create
    post 'friendship_sent_requests' => :create
    delete 'reject_friend' => :destroy
  end

  controller :logout do
    get 'logout' => :new
  end

  controller :projects do
    get 'my_projects' => :my_projects
  end

  controller :my_contributions do
    get 'my_contributions' => :get_my_contributions
  end
  resources :friendship_sent_requests

  controller :donor_requests do
    post '/donor_requests/accept' => :accept
    post '/donor_requests/reject' => :reject
    post '/donor_requests/yes_got_money' => :yes_got_money
    post '/donor_requests/no_money' => :no_money
  end
  resources :donor_requests

  resources :receiver_requests

  resources :project_fundings

  resources :projects

  resources :friendships

  resources :users

  resources :test_products

end

meethodu/app/models/project_funding.rb
class ProjectFunding < ActiveRecord::Base
end

meethodu/app/controllers/project_fundings_controller.rb
class ProjectFundingsController < ApplicationController
  # GET /project_fundings
  # GET /project_fundings.xml
  def index
    @project_fundings = ProjectFunding.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @project_fundings }
    end
  end

  # GET /project_fundings/1
  # GET /project_fundings/1.xml
  def show
    @project_funding = ProjectFunding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project_funding }
    end
  end

  # GET /project_fundings/new
  # GET /project_fundings/new.xml
  def new
    @project_funding = ProjectFunding.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project_funding }
    end
  end

  # GET /project_fundings/1/edit
  def edit
    @project_funding = ProjectFunding.find(params[:id])
  end

  # POST /project_fundings
  # POST /project_fundings.xml
  def create
    @project_funding = ProjectFunding.new(params[:project_funding])

    respond_to do |format|
      if @project_funding.save
        format.html { redirect_to(@project_funding, :notice => 'Project funding was successfully created.') }
        format.xml  { render :xml => @project_funding, :status => :created, :location => @project_funding }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project_funding.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /project_fundings/1
  # PUT /project_fundings/1.xml
  def update
    @project_funding = ProjectFunding.find(params[:id])

    respond_to do |format|
      if @project_funding.update_attributes(params[:project_funding])
        format.html { redirect_to(@project_funding, :notice => 'Project funding was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project_funding.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /project_fundings/1
  # DELETE /project_fundings/1.xml
  def destroy
    @project_funding = ProjectFunding.find(params[:id])
    @project_funding.destroy

    respond_to do |format|
      format.html { redirect_to(project_fundings_url) }
      format.xml  { head :ok }
    end
  end
end

meethodu/app/helpers/project_fundings_helper.rb
module ProjectFundingsHelper
end

meethodu/app/views/project_fundings/_form.html.erb
<%= form_for(@project_funding) do |f| %>
  <% if @project_funding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_funding.errors.count, "error") %> prohibited this project_funding from being saved:</h2>

      <ul>
      <% @project_funding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br />
    <%= f.text_field :receiver_id %>
  </div>
  <div class="field">
    <%= f.label :recommender_id %><br />
    <%= f.text_field :recommender_id %>
  </div>
  <div class="field">
    <%= f.label :donor_id %><br />
    <%= f.text_field :donor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

meethodu/app/views/project_fundings/edit.html.erb
<h1>Editing project_funding</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_funding %> |
<%= link_to 'Back', project_fundings_path %>

meethodu/app/views/project_fundings/index.html.erb
<h1>Listing project_fundings</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Receiver</th>
    <th>Recommender</th>
    <th>Donor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_fundings.each do |project_funding| %>
  <tr>
    <td><%= project_funding.project_id %></td>
    <td><%= project_funding.receiver_id %></td>
    <td><%= project_funding.recommender_id %></td>
    <td><%= project_funding.donor_id %></td>
    <td><%= link_to 'Show', project_funding %></td>
    <td><%= link_to 'Edit', edit_project_funding_path(project_funding) %></td>
    <td><%= link_to 'Destroy', project_funding, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project funding', new_project_funding_path %>

meethodu/app/views/project_fundings/new.html.erb
<h1>New project_funding</h1>

<%= render 'form' %>

<%= link_to 'Back', project_fundings_path %>

meethodu/app/views/project_fundings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @project_funding.project_id %>
</p>

<p>
  <b>Receiver:</b>
  <%= @project_funding.receiver_id %>
</p>

<p>
  <b>Recommender:</b>
  <%= @project_funding.recommender_id %>
</p>

<p>
  <b>Donor:</b>
  <%= @project_funding.donor_id %>
</p>


<%= link_to 'Edit', edit_project_funding_path(@project_funding) %> |
<%= link_to 'Back', project_fundings_path %>